// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primeNumberDecompositon/primepb/prime.proto

package primepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimeManytimesRequest struct {
	Value                int32    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeManytimesRequest) Reset()         { *m = PrimeManytimesRequest{} }
func (m *PrimeManytimesRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeManytimesRequest) ProtoMessage()    {}
func (*PrimeManytimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0657058053287e28, []int{0}
}

func (m *PrimeManytimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeManytimesRequest.Unmarshal(m, b)
}
func (m *PrimeManytimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeManytimesRequest.Marshal(b, m, deterministic)
}
func (m *PrimeManytimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeManytimesRequest.Merge(m, src)
}
func (m *PrimeManytimesRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeManytimesRequest.Size(m)
}
func (m *PrimeManytimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeManytimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeManytimesRequest proto.InternalMessageInfo

func (m *PrimeManytimesRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PrimeManytimesResponse struct {
	Reslut               int32    `protobuf:"varint,1,opt,name=reslut,proto3" json:"reslut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeManytimesResponse) Reset()         { *m = PrimeManytimesResponse{} }
func (m *PrimeManytimesResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeManytimesResponse) ProtoMessage()    {}
func (*PrimeManytimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0657058053287e28, []int{1}
}

func (m *PrimeManytimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeManytimesResponse.Unmarshal(m, b)
}
func (m *PrimeManytimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeManytimesResponse.Marshal(b, m, deterministic)
}
func (m *PrimeManytimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeManytimesResponse.Merge(m, src)
}
func (m *PrimeManytimesResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeManytimesResponse.Size(m)
}
func (m *PrimeManytimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeManytimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeManytimesResponse proto.InternalMessageInfo

func (m *PrimeManytimesResponse) GetReslut() int32 {
	if m != nil {
		return m.Reslut
	}
	return 0
}

func init() {
	proto.RegisterType((*PrimeManytimesRequest)(nil), "prime.PrimeManytimesRequest")
	proto.RegisterType((*PrimeManytimesResponse)(nil), "prime.PrimeManytimesResponse")
}

func init() {
	proto.RegisterFile("primeNumberDecompositon/primepb/prime.proto", fileDescriptor_0657058053287e28)
}

var fileDescriptor_0657058053287e28 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2e, 0x28, 0xca, 0xcc,
	0x4d, 0xf5, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x72, 0x49, 0x4d, 0xce, 0xcf, 0x2d, 0xc8, 0x2f, 0xce,
	0x2c, 0xc9, 0xcf, 0xd3, 0x07, 0x8b, 0x17, 0x24, 0x41, 0x68, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c,
	0x21, 0x56, 0x30, 0x47, 0x49, 0x97, 0x4b, 0x34, 0x00, 0xc4, 0xf0, 0x4d, 0xcc, 0xab, 0x2c, 0xc9,
	0xcc, 0x4d, 0x2d, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x0d, 0x4b,
	0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x94, 0x0c, 0xb8, 0xc4,
	0xd0, 0x95, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0xe7,
	0x94, 0x96, 0x40, 0x35, 0x40, 0x79, 0x46, 0x89, 0x5c, 0x3c, 0x60, 0x1d, 0xc1, 0xa9, 0x45, 0x65,
	0x99, 0xc9, 0xa9, 0x42, 0x81, 0x5c, 0x7c, 0x70, 0x13, 0x42, 0x40, 0x26, 0x08, 0xc9, 0xe8, 0x41,
	0xdc, 0x85, 0xd5, 0x1d, 0x52, 0xb2, 0x38, 0x64, 0x21, 0xd6, 0x2a, 0x31, 0x18, 0x30, 0x3a, 0x71,
	0x46, 0xb1, 0x43, 0x7d, 0x98, 0xc4, 0x06, 0xf6, 0x9c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x68,
	0x43, 0x34, 0xc5, 0x0b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeServiceClient is the client API for PrimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeServiceClient interface {
	PrimeManyTimes(ctx context.Context, in *PrimeManytimesRequest, opts ...grpc.CallOption) (PrimeService_PrimeManyTimesClient, error)
}

type primeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeServiceClient(cc grpc.ClientConnInterface) PrimeServiceClient {
	return &primeServiceClient{cc}
}

func (c *primeServiceClient) PrimeManyTimes(ctx context.Context, in *PrimeManytimesRequest, opts ...grpc.CallOption) (PrimeService_PrimeManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeService_serviceDesc.Streams[0], "/prime.PrimeService/PrimeManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeServicePrimeManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeService_PrimeManyTimesClient interface {
	Recv() (*PrimeManytimesResponse, error)
	grpc.ClientStream
}

type primeServicePrimeManyTimesClient struct {
	grpc.ClientStream
}

func (x *primeServicePrimeManyTimesClient) Recv() (*PrimeManytimesResponse, error) {
	m := new(PrimeManytimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeServiceServer is the server API for PrimeService service.
type PrimeServiceServer interface {
	PrimeManyTimes(*PrimeManytimesRequest, PrimeService_PrimeManyTimesServer) error
}

// UnimplementedPrimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeServiceServer struct {
}

func (*UnimplementedPrimeServiceServer) PrimeManyTimes(req *PrimeManytimesRequest, srv PrimeService_PrimeManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeManyTimes not implemented")
}

func RegisterPrimeServiceServer(s *grpc.Server, srv PrimeServiceServer) {
	s.RegisterService(&_PrimeService_serviceDesc, srv)
}

func _PrimeService_PrimeManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeManytimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeServiceServer).PrimeManyTimes(m, &primeServicePrimeManyTimesServer{stream})
}

type PrimeService_PrimeManyTimesServer interface {
	Send(*PrimeManytimesResponse) error
	grpc.ServerStream
}

type primeServicePrimeManyTimesServer struct {
	grpc.ServerStream
}

func (x *primeServicePrimeManyTimesServer) Send(m *PrimeManytimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeService",
	HandlerType: (*PrimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeManyTimes",
			Handler:       _PrimeService_PrimeManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primeNumberDecompositon/primepb/prime.proto",
}
